package com.definex.task_management.enums;


public enum Permission {
    ADMIN_USER_MANAGEMENT,

    DEPARTMENT_PROJECT_MANAGEMENT,

    PROJECT_CREATE,
    PROJECT_READ,
    PROJECT_UPDATE,
    PROJECT_DELETE,

    TASK_CREATE,
    TASK_READ,
    TASK_UPDATE,
    TASK_DELETE,
    TASK_ASSIGN,
    TASK_CHANGE_STATE,
    TASK_CHANGE_PRIORITY,

    COMMENT_CREATE,
    COMMENT_READ,
    COMMENT_UPDATE,
    COMMENT_DELETE,

    ATTACHMENT_CREATE,
    ATTACHMENT_READ,
    ATTACHMENT_DELETE,
    ATTACHMENT_UPDATE
}